sudo: required
services:
  - docker

before_install:
  - docker build -t developernaywin93/docker-react-nginx -f Dockerfile.dev .

script:
  - docker run developernaywin93/docker-react-nginx npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-nginx"
  env: "DockerReactNginx-env"
  bucket_name: "elasticbeanstalk-us-east-2-029734481635"
  bucket_path: "docker-react-nginx"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"